# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Taylor Phillips, Just Like The Movies
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Taylor Phillips, new single "Just Like the Movies" out now!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taylorphillipsofficial.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

albumart: app/images/just-like-the-movies-cover.jpg
albumartsmall: app/images/just-like-the-movies-cover-1200.jpg

apple: https://itunes.apple.com/us/album/just-like-the-movies-single/1391232367
google: https://play.google.com/store/music/album/Taylor_Phillips_Just_Like_the_Movies?id=Bszjmml35ipepx5fhc5uvja5hea&hl=en
amazon: https://www.amazon.com/Just-Like-Movies-Taylor-Phillips/dp/B07DD2FNZD/
itunes: https://itunes.apple.com/us/album/just-like-the-movies/1391232367?i=1391232633
spotify: https://open.spotify.com/track/6NtYbYDCv14uxVwd7xjTsF?si=bwcJkvE8RJmZSzSD9MzV-A
